# Generated by Django 4.2 on 2023-05-06 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_branch_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="mobile",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(9999999999),
                    django.core.validators.MinValueValidator(1000000000),
                ]
            ),
        ),
    ]
