# Generated by Django 4.2 on 2023-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_branch_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="mobile",
            field=models.CharField(max_length=10),
        ),
    ]
